name: SimpleDynamicLight
version: '3.0'
main: com.github.K4RUNIO.simpleDynamicLight.SimpleDynamicLight
api-version: '1.21'
authors: [ Karunio, Doom2615 ]
description: Simple plugin that will add Dynamic Light to your server
commands:
  dynlight:
    description: Toggle dynamic lighting on or off.
    usage: /dynlight <on|off|reload>
permissions:
  simpledynamiclight.reload:
    description: Allows reloading the SimpleDynamicLight plugin.
    default: op
